name: Build and publish Docker image

on:
  push:
    branches: [ master ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: maxhorstmann
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        registry: https://hub.docker.com
        repository: maxhorstmann/githubactionstest
        tags: latest
        push: true 
